// The ship's hull art (assets/ships/*.png, generated by tools/ships/cormorant.py) and the shared rig
// builder: TB-6 drill unit + clamp arms + CORMORANT, at run-world offsets from an origin, so the run,
// the cutscenes, the concourse bay and the rig bay all draw the exact same rig.
// [C] The drill is only seen attached ON THE JOB: off the job (station, rig bay, launch, the clean exit)
// the ship and the leased TB-6 are drawn apart with shipParts() / drillParts().
import { LAYOUT as L } from '../config.js';

export const SHIP_TEX = { hull: 'cormorant', clamps: 'cormorant_clamps', deck: 'cormorant_deck' };

export function preloadShipArt(scene) {
  for (const k of Object.values(SHIP_TEX)) scene.load.image(k, `assets/ships/${k}.png`);
}

/** A hull-frame image (hull or clamps) placed so the coupling face sits at (x, y). */
export function hullImage(scene, key, x, y) {
  const A = L.ART;
  return scene.add.image(x, y, key).setOrigin(A.ox / A.w, A.oy / A.h);
}

/**
 * Rig parts as images relative to an origin at run world (90, oy): [clamps, drillunit, cutter, hull].
 * Put them in a container at the origin. opts: unit (drill unit + clamps, default true).
 * Returns { parts, cutter }.
 */
export function rigParts(scene, oy = 260, { unit = true } = {}) {
  const DU = L.DRILL_UNIT, F = L.FACE, parts = [];
  let cutter = null;
  if (unit) {
    cutter = scene.add.image(0, L.DRILL_TIP_Y - oy, 'cutter0').setOrigin(0.5, 0);
    parts.push(hullImage(scene, SHIP_TEX.clamps, F.x - 90, F.y - oy), scene.add.image(DU.x - 90, DU.bodyTop - oy, 'drillunit').setOrigin(0), cutter);
  }
  parts.push(hullImage(scene, SHIP_TEX.hull, F.x - 90, F.y - oy));
  return { parts, cutter };
}

/** The leased TB-6 on its own (no clamps: those are the ship's arms). Same origin convention as rigParts. */
export function drillParts(scene, oy = 260) {
  const DU = L.DRILL_UNIT;
  const cutter = scene.add.image(0, L.DRILL_TIP_Y - oy, 'cutter0').setOrigin(0.5, 0);
  return { parts: [scene.add.image(DU.x - 90, DU.bodyTop - oy, 'drillunit').setOrigin(0), cutter], cutter };
}

/** CORMORANT alone, optionally with its clamp arms + umbilicals (returned separately so they can open/close). */
export function shipParts(scene, oy = 260, { clamps = false } = {}) {
  const F = L.FACE;
  const c = clamps ? hullImage(scene, SHIP_TEX.clamps, F.x - 90, F.y - oy) : null;
  const hull = hullImage(scene, SHIP_TEX.hull, F.x - 90, F.y - oy);
  return { parts: c ? [c, hull] : [hull], clamps: c, hull };
}
